TECHNOLOGIES_NAME = [
    "Python",
    "JavaScript",
    "Java",
    "React",
    "Node",
    "Angular",
    "Django",
    "Flask",
    "Ruby",
    "C#",
    ".NET",
    "SQL",
    "MongoDB",
    "Docker",
    "Kubernetes",
    "AWS",
    "Azure",
    "GCP",
    "DevOps",
    "Git",
    "TypeScript",
    "Vue",
    "Spring Framework",
    "TensorFlow",
    "REST",
    "PostgreSQL",
    "API",
    "FastAPI",
    "Elasticsearch",
    "Redis",
    "Webpack",
    "Docker",
    "REST",
    "DRF",
    "OpenShift",
    "OracleDB",
    "Kafka",
    "OOP",
    "HTML",
    "CSS",
    "JS",
    " ML",
]

EXPERIENCE_YEARS = {"студента": 0, "1": 1, "2": 2, "3": 3, "4": 4, "5": 5}
